fixes #54,  pipfile python version fix
intern-space-program/ksp pull request #55
Opened 2020-07-01 22:50 UTC by cadojo

## Types of Changes

Please check off the kinds of changes included in this pull request.

### Procedures
- [ ] Adds new procedure documents
- [ ] Modifies existing procedures
- [ ] Removes procedures

### Vehicle
- [ ] Adds a new vehicle
- [ ] Modifies an existing vehicle
- [ ] Removes a vehicle

### Code
- [ ] Adds new code
- [ ] Modifies existing code
- [ ] Removes code

### Unit Tests
- [ ] Adds unit tests
- [ ] Modifies existing unit tests
- [ ] Removes unit tests

### Miscellaneous
- [ ] Add/modify supporting documents (e.g. README.md files, community documents, templates)
- [X] Other (explain in comment below)

## Did you make sure to...

### Vehicles
- [ ] ensure modified vehicles don't break existing event sequence code
- [ ] notify teams whose scripts depend on that vehicle file
- [ ] N/A

### Code
- [ ] add safety checks for common crashes (e.g. division by zero)
- [ ] N/A

### Unit Tests
- [ ] add new unit tests for any new code
- [ ] N/A

### Sequence Controller Tests
- [ ] run the code with the existing sequence controllers and ensure nothing breaks
- [ ] N/A

### Miscellaneous
- [X] connect the issues this pull request closes (**required**)

2020-07-01 22:57 UTC, cadojo commented
This PR is a __draft__, please do not merge yet.

2020-07-01 23:57 UTC, cadojo commented
This PR is no longer a __draft__. Issue #54 should be fixed.

2020-07-05 02:10 UTC, mdbernard requested changes

2020-07-05 02:10 UTC, mdbernard commented on Pipfile
> -python_version = "3.7"
I had changed the python version to 3.7 since it looked like a bunch of common packages haven't been updated yet. All the ones we're currently planning on using are, but if we wanted to add in others later it could cause trouble. I think a better solution to the requirements issue would just be to replace the numpy version with one compatible with python 3.7.

2020-07-05 02:10 UTC, mdbernard commented on README.md
> +From the command line, run `$ pip install -r requirements.txt` from the `ksp` directory.
👍

2020-07-05 02:10 UTC, mdbernard commented on README.md
> +`$ pipenv install --python python3.8`
Same deal here. I think we should stick with 3.7, for reasons specified in my other comment.

2020-07-06 17:44 UTC, mdbernard approved these changes

2020-07-06 17:44 UTC, merged